# .github/workflows/deploy-backend-to-eb.yml

name: Deploy Backend to Elastic Beanstalk

on:
  push:
    branches:
      - master
    paths:
      - 'backend/**' 

env:
  EB_APPLICATION_NAME: skynotes-api
  EB_ENVIRONMENT_NAME: skynotes-api-env-v2
  EB_REGION: eu-central-1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Navigate to backend directory
      run: cd backend

    - name: Install backend dependencies
      run: npm install
      working-directory: backend

    - name: Create .zip deployment package
      run: |
          zip -r deploy.zip . \
          -x "node_modules/*" \
          -x ".git/*" \
          -x ".github/*" \
          -x ".env*" \
          -x "config.json" \
          -x "dist/*" \
          -x ".cache/*" \
          -x "logs/*" \
          -x "*.log" \
          -x "npm-debug.log*" \
          -x "yarn-debug.log*" \
          -x "yarn-error.log*" \
          -x "pnpm-debug.log*" \
          -x "lerna-debug.log*" \
          -x "tmp/*" \
          -x "temp/*" \
          -x ".DS_Store" \
          -x "Thumbs.db" \
          -x ".idea/*" \
          -x ".vscode/*" \
          -x "*.suo" \
          -x "*.ntvs*" \
          -x "*.njsproj" \
          -x "*.sln" \
          -x "*.swp" \
          -x "*.vim" \
          -x "_vimrc" \
          -x "*.bak" \
          -x "*.orig" \
          -x "*.local" \
          -x ".eslintconfig.mjs" \
          -x ".elasticbeanstalk/*" \
          -x ".ebextensions/*"
      working-directory: backend 

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.EB_REGION }}

    - name: Deploy to Elastic Beanstalk
      uses: aws-actions/elasticbeanstalk-deploy@v1
      with:
        application_name: ${{ env.EB_APPLICATION_NAME }}
        environment_name: ${{ env.EB_ENVIRONMENT_NAME }}
        version_label: github-actions-${{ github.sha }}
        source_bundle: backend/deploy.zip
        region: ${{ env.EB_REGION }}

    - name: Verify Deployment (Optional)
      run: echo "Deployment to Elastic Beanstalk complete!"
